require_relative "./ESPNScraper/version"
require_relative "./ESPNScraper/cli"
require_relative "./ESPNScraper/article"
require_relative "./ESPNScraper/scraper"
require "open-uri"
require "nokogiri"
require "pry"
