require_relative "../lib/version.rb"
require_relative "../lib/cli.rb"
require_relative "../lib/article.rb"
require_relative "../lib/scraper.rb"
require_relative "../lib/teams.rb"
require "open-uri"
require "nokogiri"
require "colorize"
require 'tty-prompt'
